import { OperationKind } from "@azguardwallet/types";

export const aztecMethods: OperationKind[] = [
    "aztec_simulateTx",
    "aztec_simulateUtility",
    "aztec_profileTx",
    "aztec_sendTx",
    "aztec_getContractClassMetadata",
    "aztec_getContractMetadata",
    "aztec_registerContract",
    "aztec_registerContractClass",
    "aztec_proveTx",
    "aztec_getNodeInfo",
    "aztec_getPXEInfo",
    "aztec_getCurrentBaseFees",
    "aztec_updateContract",
    "aztec_registerSender",
    "aztec_getSenders",
    "aztec_removeSender",
    "aztec_getTxReceipt",
    "aztec_getPrivateEvents",
    "aztec_getPublicEvents",
    "aztec_getCompleteAddress",
    "aztec_getAddress",
    "aztec_getChainId",
    "aztec_getVersion",
    "aztec_createTxExecutionRequest",
    "aztec_createAuthWit",
];
